variable "AppEnvPrefix" {}
variable "StrapiImage" {}
variable "StrapiContainerCpu" {}
variable "StrapiContainerMemory" {}
variable "Host" {}
variable "AppKeys" {}
variable "ApiTokenSalt" {}
variable "AdminJwtSecret" {}
variable "TransferTokenSalt" {}
variable "DatabaseClient" {}
variable "JwtSecret" {}
variable "DatabaseHost" {}
variable "DatabasePort" {}
variable "DatabaseName" {}
variable "DatabaseUserName" {}
variable "DatabasePassword" {}
variable "DatabaseSslEnable" {}
variable "ClusterName" {}
variable "TaskDefinition" {}
variable "StrapiRollingMaxPercent" {}
variable "StrapiMinHealthyPercent" {}
variable "VpcId" {}
variable "StrapiHealthCheckPath" {}
variable "AlbListenerArn80" {}
variable "StrapiAlbHostHeader" {}
variable "AlbListenerArn443" {}
variable "StrapiLisenterPriority" {}
variable "NodeEnv" {}
variable "AppEnv" {}
variable "AwsAccessKey" {}
variable "AwsAccessSecretKey" {}
variable "AwsRegion" {}
variable "AwsBucket" {}